const DB_FILES=['weapons','armors','items','skills','states','enemies','actors','troops'];
const rarity={0:['Starter','#CCCCCC'],1:['Common','#ffffff'],2:['Uncommon','#78ff78'],3:['Rare','#6b99e3'],4:['Epic','#ff78dd'],5:['Legendary','#ffca2b'],6:['Mythic','#7b68ee']};
let db={}, config={}, usedIds=[];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function noteTag(note,key){const m=String(note||'').match(new RegExp('<'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*:\\s*([^>]+)>','i'));return m?m[1].trim():''}
function allTags(note,key){const r=new RegExp('<'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*:\\s*([^>]+)>','gi'),a=[];let m;while((m=r.exec(String(note||''))))a.push(m[1].trim());return a}
function parseRarity(note){const m=String(note||'').match(/<Rarity:\s*(\d+)>/i);return m?Number(m[1]):null}
function category(e){let c=noteTag(e.note,'EnemyCategory'); if(c)return c.toLowerCase(); const n=String(e.note||'').toLowerCase(); if(/abyss\s+boss/.test(n))return 'abyss boss'; if(/mini-boss/.test(n))return 'mini boss'; if(/\(boss\)/.test(n))return 'boss'; return 'uncategorized'}
function params(e){return e.params||[]}
const paramNames=['HP','MP','ATK','DEF','M.ATK','M.DEF','AGI','LUK'];
function statRows(e){const p=params(e), max=Math.max(...p,1); return paramNames.map((n,i)=>`<div class="bar-row"><span class="bar-label">${n}</span><div class="bar-track"><div class="bar-fill" data-width="${Math.max(2,Math.round((p[i]||0)/max*100))}%" style="background:${['#e34e78','#b97ae9','#f0c64f','#63b0e9','#bd79ed','#62d58e','#62d58e','#ed4ac7'][i]}"></div></div><span class="bar-value">${p[i]??0}</span></div>`).join('')}
function icon(idx){if(idx==null)return ''; const x=idx%16,y=Math.floor(idx/16); return `<span class="icon" style="background-position:-${x*32}px -${y*32}px" title="Icon ${idx}"></span>`}
function rarityTag(r){if(r==null)return '';const x=rarity[r]||['Other','#7b879b'];return `<span class="tag" style="color:${x[1]};border-color:${x[1]}55;background:${x[1]}14">${esc(x[0])} · T${r}</span>`}
function enemyTag(c){const map={'normal':['normal','tag'],'champion':['champion','tag'],'elite':['elite','tag elite'],'elite champion':['elite champion','tag elite'],'mini boss':['mini boss','tag mini'],'boss':['boss','tag boss'],'abyss boss':['abyss boss','tag abyss'],'abyss normal':['abyss normal','tag abyss'],'abyss champion':['abyss champion','tag abyss'],'abyss elite':['abyss elite','tag abyss'],'abyss elite champion':['abyss elite champion','tag abyss'],'uncategorized':['uncategorized','tag']};let x=map[c]||map.uncategorized;return `<span class="${x[1]}">${x[0]}</span>`}
function dataByName(arr,id){return (db[arr]||[]).find(x=>x&&x.id===id)}
function cleanInfo(note){let s=String(note||'');let m=s.match(/<Info:\s*([\s\S]*?)>/i); if(!m)return ''; s=m[1].replace(/\\[.!]/g,' ').replace(/\\n/g,' ').replace(/\\c\[\d+\]/g,'').replace(/\s+/g,' ').trim(); return s}
function levelRange(e){let a=noteTag(e.note,'Minimum Level'),b=noteTag(e.note,'Maximum Level');return a&&b?`${a}-${b}`:a||'—'}
function drops(e){const rows=[];(e.dropItems||[]).forEach(d=>{if(!d.denominator)return;let name=d.kind===1?dataByName('items',d.dataId)?.name:d.kind===2?dataByName('weapons',d.dataId)?.name:d.kind===3?dataByName('armors',d.dataId)?.name:'Nothing';if(name)rows.push([name,Math.round(100/d.denominator)])}); return rows}
function nav(active){document.querySelectorAll('.side-links a,.topnav a').forEach(a=>a.classList.toggle('active',a.dataset.page===active))}
function raritySidebar(){return Object.entries(rarity).map(([t,x])=>`<div class="rarity-row"><i class="rarity-dot" style="background:${x[1]}"></i>${x[0]}<span class="rarity-tier">T${t}</span></div>`).join('')}
function shell(active,content){nav(active); return `<header class="topbar"><a class="brand" href="#home"><span class="brand-mark">IE</span><span><div class="brand-title">INFINITE ECHOES</div><div class="brand-sub">IN THE INFINITE ABYSS</div></span></a><nav class="topnav"><a data-page="home" href="#home">Home</a><a data-page="enemies" href="#enemies">Enemies</a><a data-page="weapons" href="#weapons">Weapons</a><a data-page="armors" href="#armors">Armor</a><a data-page="items" href="#items">Items</a><a data-page="skills" href="#skills">Skills</a><a data-page="actors" href="#actors">Characters</a></nav><div class="top-actions"><span class="ghost">SPOILERS OFF</span></div></header><div class="layout"><aside class="sidebar"><p class="eyebrow">Navigate</p><div class="side-links"><a data-page="home" href="#home">Home</a><a data-page="enemies" href="#enemies">Enemies</a><a data-page="weapons" href="#weapons">Weapons</a><a data-page="armors" href="#armors">Armor</a><a data-page="items" href="#items">Items</a><a data-page="skills" href="#skills">Skills</a><a data-page="actors" href="#actors">Characters</a></div><p class="eyebrow">Rarity Scale</p><div class="rarity-list">${raritySidebar()}</div><p class="sidebar-note">Rarities apply to gear only.<br>Enemies use their own category ladder.</p></aside><main class="main"><div class="content">${content}</div></main></div><footer class="footer"><span>${esc(config.gameTitle)} · in-development codex</span><span>Numbers change as the game is balanced <span class="socials">${socialLinks()}</span></span></footer><div id="modal" class="modal"></div>`}
function socialLinks(){return Object.entries(config.socials||{}).filter(([,u])=>u).map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noreferrer">${esc(n)}</a>`).join('')}
function home(){const cards=[['Weapons','weapons','Equipment, tiers, icons, descriptions and prices.'],['Armor','armors','Gear, passive effects and rarity tiers.'],['Items','items','Consumables, key items and utility entries.'],['Skills','skills','Player and enemy skills from the database.'],['Status Effects','states','States, traits and gameplay conditions.'],['Characters','actors','Party members and character data.'],['Enemies','enemies',`${usedIds.length} named enemies currently used by Troops.json.`]];return shell('home',`<section class="home-hero fade"><div class="page-kicker">${esc(config.subtitle)}</div><h1>${esc(config.gameTitle)}</h1><p>A living reference for weapons, armor, items, skills, status effects, characters, and the enemies actually represented by the current game database.</p><div class="hero-meta"><span class="pill">VERSION ${esc(config.version)}</span><span class="pill">UPDATED ${esc(config.lastUpdated)}</span><span class="pill">${esc(config.dataStatus)}</span></div></section><div class="category-grid fade">${cards.map(c=>`<a class="category" href="#${c[1]}"><h3>${c[0]}</h3><p>${c[2]}</p></a>`).join('')}</div><section style="margin-top:22px"><p class="eyebrow">Version History</p><div class="empty">${(config.versionHistory||[]).map(v=>`<div style="display:flex;justify-content:space-between;gap:15px;padding:8px 0;border-bottom:1px solid #1c2534"><span><b>${esc(v.version)}</b> · ${esc(v.changes)}</span><span class="version">${esc(v.date)}</span></div>`).join('')}</div></section>`)}
function listPage(type,title,desc,renderer,filters=[]){return shell(type,`<div class="page-head fade"><div><div class="page-kicker">Field Codex · Database</div><h1 class="page-title">${title}</h1><p class="page-desc">${desc}</p></div><input class="search" id="search" placeholder="Search ${title.toLowerCase()}..." /></div>${filters.length?`<div class="filters" id="filters">${filters.map((f,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${esc(f[0])}">${esc(f[1])}</button>`).join('')}</div>`:''}<div class="grid fade" id="cards"></div>`)}
function renderCards(type){const q=($('#search')?.value||'').toLowerCase();let arr=db[type]||[];if(type==='enemies')arr=arr.filter(e=>e&&usedIds.includes(e.id)&&e.name);else arr=arr.filter(x=>x&&x.name&&!/^=+/.test(x.name)); const active=$('.filter.active')?.dataset.filter;if(type==='enemies'&&active&&active!=='all')arr=arr.filter(e=>category(e)===active);arr=arr.filter(x=>(x.name+' '+(x.description||'')+' '+(x.note||'')).toLowerCase().includes(q));const el=$('#cards'); if(!el)return;el.innerHTML=arr.map((x,i)=>card(type,x,i)).join('')||'<div class="empty">No matching entries.</div>'; el.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>openDetail(type,Number(c.dataset.id))));}
function card(type,x,i){if(type==='enemies'){let c=category(x),p=params(x),art=`assets/enemies/${x.id}.png`;return `<article class="card" data-id="${x.id}"><div class="topline">${enemyTag(c)}<span class="zone">ZONE ${esc(noteTag(x.note,'Tattle Category').replace(/zone\s*/i,'' )||'—')}</span></div><h3>${esc(x.name)}</h3>${c==='uncategorized'?'<p>Category not tagged in the current database.</p>':`<div class="statline"><span>HP <b>${p[0]}</b></span><span>ATK <b>${p[2]}</b></span><span>DEF <b>${p[3]}</b></span><span class="lv">LV ${levelRange(x)}</span></div>`}${(usedIds.includes(x.id)&&x.id<999&&art)?`<img class="art" src="${art}" onerror="this.style.display='none'">`:''}</article>`}
let r=parseRarity(x.note); let art=type==='weapons'?`assets/weapons/${x.id}.png`:'';return `<article class="card" data-id="${x.id}"><div class="topline">${rarityTag(r)}<span class="zone">#${x.id}</span></div>${icon(x.iconIndex)} <h3 style="display:inline;vertical-align:middle">${esc(x.name)}</h3>${art?`<img class="weapon-art" src="${art}" onerror="this.style.display='none'">`:''}<p>${esc(x.description||'No description recorded.')}</p><div class="statline"><span>${type==='weapons'||type==='armors'?'PRICE':'ID'} <b>${type==='weapons'||type==='armors'?x.price??0:x.id}</b></span>${r!=null?`<span style="color:${rarity[r]?.[1]}">T${r}</span>`:''}</div></article>`}
function openDetail(type,id){const x=dataByName(type,id);if(!x)return;let body='';if(type==='enemies')body=enemyDetail(x);else body=genericDetail(type,x);$('#modal').innerHTML=`<div class="modal-box"><div class="modal-top"><span class="version">${esc(type.toUpperCase())} · #${id}</span><button class="close">Close</button></div><div class="modal-body">${body}</div></div>`;$('#modal').classList.add('open');$('.close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};setTimeout(animateBars,80)}
function enemyDetail(e){const p=params(e),c=category(e),dr=drops(e);let growth=['maxhp','maxmp','atk','def','mat','mdf','agi','exp','gold'].map(k=>{let t=noteTag(e.note,k+' Flat');return t?`<div class="code-line">&lt;${k} Flat: ${esc(t)}&gt;</div>`:null}).filter(Boolean).join('');return `<div class="detail"><div class="detail-head">${enemyTag(c)} <span class="zone">ZONE ${esc(noteTag(e.note,'Tattle Category')||'—')}</span><h1>${esc(e.name)}</h1><p>${esc(cleanInfo(e.note)||'No enemy information recorded.')}</p></div><div class="detail-body"><section class="stats-panel"><div class="section-title">Base Stats</div>${statRows(e)}<div class="reward-grid"><div class="reward"><strong>${levelRange(e)}</strong><small>LEVEL</small></div><div class="reward"><strong>${e.exp??0}</strong><small>EXP</small></div><div class="reward"><strong>${e.gold??0}</strong><small>GOLD</small></div></div><div class="section-title" style="margin-top:18px">JP / Rewards</div><p class="muted">JP ${esc(noteTag(e.note,'JP')||'0')} · Base EXP ${e.exp??0} · Base Gold ${e.gold??0}</p></section><section class="growth-panel"><div class="section-title">Growth / Level</div><div class="code-list">${growth||'<div class="code-line" style="color:#66768d">No growth tags recorded.</div>'}</div><div class="section-title" style="margin-top:18px">Drops</div>${dr.length?dr.map(d=>`<div class="drop-row"><span style="color:#63dc91">${d[1]}%</span><div class="drop-track"><div class="drop-fill" style="width:${Math.min(100,d[1])}%"></div></div><span>${esc(d[0])}</span></div>`).join(''):'<span class="muted">No standard drop data recorded.</span>'}<div class="section-title" style="margin-top:20px">Traits / Notes</div><p class="muted">${esc((e.note||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').slice(0,650))}</p></section></div></div>`}
function genericDetail(type,x){const r=parseRarity(x.note);return `<div class="detail"><div class="detail-head">${icon(x.iconIndex)} ${rarityTag(r)}<h1>${esc(x.name)}</h1><p>${esc(x.description||'No description recorded.')}</p></div><div class="detail-body"><section class="stats-panel"><div class="section-title">Database Entry</div><div class="reward-grid"><div class="reward"><strong>#${x.id}</strong><small>ID</small></div><div class="reward"><strong>${x.price??'—'}</strong><small>PRICE</small></div><div class="reward"><strong>${r!=null?'T'+r:'—'}</strong><small>RARITY</small></div></div><div class="section-title" style="margin-top:20px">Parameters</div><div class="code-list">${Object.entries(x.params||{}).filter(([,v])=>v).map(([k,v])=>`<div class="code-line" style="color:#9eb1c9">${esc(k)}: ${esc(v)}</div>`).join('')||'<div class="code-line" style="color:#66768d">No non-zero parameters recorded.</div>'}</div></section><section class="growth-panel"><div class="section-title">Notes</div><p class="muted">${esc((x.note||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,1500)||'No notes recorded.')}</p></section></div></div>`}
function animateBars(){document.querySelectorAll('.bar-fill').forEach((b,i)=>{requestAnimationFrame(()=>setTimeout(()=>b.style.width=b.dataset.width,i*35))})}
function page(type){if(type==='home')return home();if(type==='enemies'){let cats=[['all','All'],['normal','Normal'],['champion','Champion'],['elite','Elite'],['elite champion','Elite Champion'],['mini boss','Mini Boss'],['boss','Boss'],['abyss boss','Abyss Boss']];return listPage(type,'Enemy Bestiary',`${usedIds.length} named enemies are currently referenced by Troops.json. Only those enemy IDs are shown; stale/missing troop references are not invented into entries.`,null,cats)}let meta={weapons:['Weapons','Weapon database with RPG Maker icons, tier colors, prices, descriptions and available artwork.'],armors:['Armor & Accessories','Armor, passive gear and accessories organized by their current rarity tags.'],items:['Items','Consumables, key items and utility entries from the current database.'],skills:['Skills','Skills currently present in the RPG Maker skill database.'],states:['Status Effects','States and gameplay conditions from the current database.'],actors:['Characters','Actors currently present in the project database.']};let m=meta[type];return listPage(type,m[0],`${(db[type]||[]).filter(x=>x&&x.name&&!/^=+/.test(x.name)).length} database entries. ${m[1]}`,null,[])}
async function load(){config=await fetch('data/site-config.json').then(r=>r.json()); for(const f of DB_FILES)db[f]=await fetch('data/'+f+'.json').then(r=>r.json()); usedIds=(await fetch('data/enemy-used-ids.json').then(r=>r.json())).usedEnemyIds||[];route()}
function route(){let t=(location.hash||'#home').slice(1).split('/')[0]||'home';document.body.innerHTML=page(t);if(t!=='home'){renderCards(t);$('#search')?.addEventListener('input',()=>renderCards(t));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCards(t)})}}
window.addEventListener('hashchange',route);load();