const DB=['weapons','armors','items','skills','states','enemies','actors','troops'];
const rarity={0:['Starter','#CCCCCC'],1:['Common','#FFFFFF'],2:['Uncommon','#78FF78'],3:['Rare','#6B99E3'],4:['Epic','#FF78DD'],5:['Legendary','#FFCA2B'],6:['Mythic','#7B68EE']};
const rarityOrder=[0,1,2,3,4,5,6];
const itemCategories={
  currency:['Currency / Materials',2,21],
  healing:['Healing',23,122],
  active:['Active Items',124,223],
  key:['Key Items',225,324],
  utility:['Utility Items',326,355]
};
let db={},config={},usedIds=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function noteTag(note,key){const safe=key.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&');const m=String(note||'').match(new RegExp('<'+safe+'\\s*:\\s*([^>]+)>','i'));return m?m[1].trim():''}
function allTags(note,key){const safe=key.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&');const r=new RegExp('<'+safe+'\\s*:\\s*([^>]+)>','gi'),a=[];let m;while((m=r.exec(String(note||''))))a.push(m[1].trim());return a}
function parseRarity(note){const m=String(note||'').match(/<Rarity:\s*(\d+)>/i);const plugin=m?Number(m[1]):null;return plugin!=null&&plugin>=1&&plugin<=7?plugin-1:null}
function cleanText(s){return String(s??'').replace(/\\c\[\d+\]/g,'').replace(/\\i\[\d+\]/g,'').replace(/\\[.!|{}]/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function icon(idx){if(idx==null||idx<0)return '';const x=idx%16,y=Math.floor(idx/16);return `<span class="icon" style="background-position:-${x*32}px -${y*32}px"></span>`}
function rarityTag(r){if(r==null)return '<span class="tag">Unassigned</span>';const x=rarity[r];return `<span class="tag" style="color:${x[1]};border-color:${x[1]}55;background:${x[1]}14">${esc(x[0])} · Tier ${r}</span>`}
function enemyCategory(e){return noteTag(e.note,'EnemyCategory').trim().toLowerCase()||'uncategorized'}
function enemyLabel(c){const labels={'normal':'Normal','champion':'Champion','elite':'Elite','elite champion':'Elite Champion','mini boss':'Mini Boss','boss':'Boss','abyss normal':'Abyss · Normal','abyss champion':'Abyss · Champion','abyss elite':'Abyss · Elite','abyss elite champion':'Abyss · Elite Champion','abyss mini boss':'Abyss · Mini Boss','abyss boss':'Abyss · Boss','uncategorized':'Uncategorized'};return labels[c]||c.replace(/\b\w/g,m=>m.toUpperCase())}
function enemyTag(c){return `<span class="tag">${esc(enemyLabel(c))}</span>`}
function levelRange(e){const a=noteTag(e.note,'Minimum Level'),b=noteTag(e.note,'Maximum Level');return a&&b?`${esc(a)}-${esc(b)}`:a?esc(a):'—'}
function dataById(type,id){const n=Number(id);return (db[type]||[]).find(x=>x&&Number(x.id)===n)}
function isHeader(x){return !x||!x.name||/^\s*[=\-_*]{4,}\s*$/.test(x.name)||/^[-=]+/.test(x.name)&&x.name.length>12}
function validEntries(type){return (db[type]||[]).filter(x=>x&&x.name&&!isHeader(x))}
function usedEnemies(){return usedIds.map(id=>dataById('enemies',id)).filter(e=>e&&e.name&&!isHeader(e))}
function nav(active){document.querySelectorAll('.side-links a,.topnav a').forEach(a=>a.classList.toggle('active',a.dataset.page===active))}
function spoilerEnabled(){return localStorage.getItem('ie-spoilers')==='on'}
function textZoom(){return Number(localStorage.getItem('ie-text-zoom')||'1.08')}
function applyPrefs(){document.body.classList.toggle('spoilers-on',spoilerEnabled());document.body.style.setProperty('--page-zoom',String(textZoom()))}
function accessDock(){return `<div class="access-dock" aria-label="Accessibility controls"><span class="access-label">View</span><button class="access-btn ${spoilerEnabled()?'spoiler-on':''}" id="spoilerToggle" data-tooltip="Toggle spoiler visibility" aria-label="Toggle spoiler visibility">${spoilerEnabled()?'SPOILERS ON':'SPOILERS OFF'}</button><span class="access-label">Text</span><button class="access-btn ${textZoom()===0.96?'active':''}" data-zoom="0.96" data-tooltip="Smaller text" aria-label="Smaller text">A−</button><button class="access-btn ${textZoom()===1.08?'active':''}" data-zoom="1.08" data-tooltip="Comfortable text" aria-label="Comfortable text">A</button><button class="access-btn ${textZoom()===1.22?'active':''}" data-zoom="1.22" data-tooltip="Larger text" aria-label="Larger text">A+</button></div>`}
function socialLinks(){const map={'Discord':'Discord02.png','YouTube':'YouTube02.png','X / Twitter':'Twitter02.png','GitHub':'GitHub02.png'};return Object.entries(config.socials||{}).filter(([,u])=>u).map(([n,u])=>`<a class="social-btn" href="${esc(u)}" target="_blank" rel="noopener noreferrer" data-tooltip="${esc(n)}" aria-label="${esc(n)}">${map[n]?`<img src="assets/${map[n]}" alt="${esc(n)}">`:`<span class="social-icon-text">${n==='itch.io'?'i':'•'}</span>`}</a>`).join('')}
function sidebar(){return `<aside class="sidebar"><p class="eyebrow">Navigate</p><div class="side-links"><a data-page="home" href="#home">Overview</a><a data-page="enemies" href="#enemies">Enemies</a><a data-page="weapons" href="#weapons">Weapons</a><a data-page="armors" href="#armors">Armor</a><a data-page="items" href="#items">Items</a><a data-page="skills" href="#skills">Skills</a><a data-page="states" href="#states">Status Effects</a><a data-page="actors" href="#actors">Characters</a></div><p class="eyebrow">Rarity Scale</p><div class="rarity-list">${rarityOrder.map(r=>`<div class="rarity-row"><i class="rarity-dot" style="background:${rarity[r][1]};color:${rarity[r][1]}"></i>${rarity[r][0]}<span class="rarity-tier">T${r}</span></div>`).join('')}</div><p class="sidebar-note">Rarity applies to equipment only. Plugin rarity values are converted to your game's Tier 0–6 scale.</p></aside>`}
function globalSearch(){return `<form class="global-search" id="globalSearch"><span>⌕</span><input id="globalSearchInput" aria-label="Search encyclopedia" placeholder="Search encyclopedia..." autocomplete="off"></form>`}
function shell(active,content){return `<header class="topbar"><a class="brand" href="#home"><span class="brand-mark">IE</span><span><div class="brand-title">INFINITE ECHOES</div><div class="brand-sub">IN THE INFINITE ABYSS</div></span></a><nav class="topnav"><a data-page="home" href="#home">Overview</a><a data-page="enemies" href="#enemies">Enemies</a><a data-page="weapons" href="#weapons">Weapons</a><a data-page="armors" href="#armors">Armor</a><a data-page="items" href="#items">Items</a><a data-page="skills" href="#skills">Skills</a><a data-page="states" href="#states">Status</a><a data-page="actors" href="#actors">Characters</a></nav>${globalSearch()}<div class="top-actions">VERSION ${esc(config.version||'0.0.0')}</div></header><div class="layout">${sidebar()}<main class="main"><div class="content">${content}</div></main></div><footer class="footer"><div><strong>${esc(config.gameTitle)}</strong><div>${esc(config.dataStatus||'Development database')}</div></div><div class="footer-right"><span>Last updated ${esc(config.lastUpdated||'—')}</span><span class="footer-community-label">Community</span><span class="socials">${socialLinks()||'<span class="social-empty">Add links in the private editor</span>'}</span></div></footer>${accessDock()}`}
function home(){const counts={weapons:equipmentEntries('weapons').length,armors:equipmentEntries('armors').length,items:itemEntries().length,skills:allPublicSkills().length,states:validEntries('states').length,actors:playableActors().length,enemies:usedEnemies().length};const cards=[['Weapons','weapons',`${counts.weapons} tiered weapon entries.`],['Armor & Accessories','armors',`${counts.armors} tiered armor and accessory entries.`],['Items','items',`${counts.items} entries organized by your RPG Maker item sections.`],['Skills','skills',`${counts.skills} player-facing skills organized by character.`],['Status Effects','states',`${counts.states} current status entries.`],['Characters','actors',`${counts.actors} playable party members.`],['Enemies','enemies',`${counts.enemies} named enemies currently referenced by Troops.json.`]];return shell('home',`<section class="home-hero fade"><div class="page-kicker">${esc(config.subtitle)}</div><h1>${esc(config.gameTitle)}</h1><p>A living reference for the things you can discover in the Abyss. Player-facing information is separated from RPG Maker implementation data, with the database's own organization carried into the encyclopedia.</p><div class="hero-meta"><span class="pill">VERSION ${esc(config.version)}</span><span class="pill">UPDATED ${esc(config.lastUpdated)}</span><span class="pill">TEXT SIZE ${Math.round(textZoom()*100)}%</span></div></section><div class="category-grid fade">${cards.map(c=>`<a class="category" href="#${c[1]}"><h3>${c[0]}</h3><p>${c[2]}</p></a>`).join('')}</div><section class="recent"><div class="section-title">Recently Cataloged</div><div class="grid">${usedEnemies().slice(-6).reverse().map(e=>card('enemies',e)).join('')||'<div class="empty">No enemy entries yet.</div>'}</div></section><section class="recent"><div class="section-title">Version History</div><div class="history">${(config.versionHistory||[]).map(v=>`<div class="history-row"><span><b>${esc(v.version)}</b> · ${esc(v.changes)}</span><span class="version">${esc(v.date)}</span></div>`).join('')}</div></section>`)}
function equipmentEntries(type){return validEntries(type).filter(x=>parseRarity(x.note)!=null)}
function itemCategory(id){for(const [key,meta] of Object.entries(itemCategories))if(id>=meta[1]&&id<=meta[2])return key;return null}
function itemEntries(){return validEntries('items').filter(x=>itemCategory(x.id))}
function skillCategory(id){if(id>=216&&id<=316)return 'hero';if(id>=318&&id<=333)return 'dog';if(id>=335&&id<=340)return 'willy';return null}
function allPublicSkills(){return validEntries('skills').filter(s=>skillCategory(s.id)&&!/(\bTEST\b|\(Old\.|GPT_|^OLD\b)/i.test(s.name)&&s.id!==333&&s.id!==334)}
function playableSkills(cat){return allPublicSkills().filter(s=>!cat||skillCategory(s.id)===cat)}
function playableActors(){return (db.actors||[]).filter(a=>a&&['Roy','Dog','Willy'].includes(a.name))}
function actorImage(a){const m={Roy:'Face_5 (Roy).png',Dog:'Face_6 (Dog).png',Willy:'Face_7 (Willy).png'};return m[a.name]?`assets/characters/${encodeURIComponent(m[a.name])}`:''}
function sortControls(type){let options=type==='enemies'?['name-az','name-za','hp-high','hp-low']:type==='weapons'||type==='armors'?['tier-low','tier-high','name-az','name-za','price-low','price-high']:['name-az','name-za','id-low','id-high'];const labels={'name-az':'Name A–Z','name-za':'Name Z–A','tier-low':'Tier Low → High','tier-high':'Tier High → Low','price-low':'Price Low → High','price-high':'Price High → Low','hp-high':'HP High → Low','hp-low':'HP Low → High','id-low':'ID Low → High','id-high':'ID High → Low'};return `<div class="sort-wrap">SORT <select class="sort-select" id="sort">${options.map(o=>`<option value="${o}">${labels[o]}</option>`).join('')}</select></div>`}
function listPage(type,title,desc,filters){return shell(type,`<div class="page-head fade"><div><div class="page-kicker">Field Codex · Database</div><h1 class="page-title">${title}</h1><p class="page-desc">${desc}</p></div><input class="search" id="search" placeholder="Search ${title.toLowerCase()}..." /></div>${filters?`<div class="filters" id="filters">${filters.map((f,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${esc(f[0])}">${esc(f[1])}</button>`).join('')}</div>`:''}<div class="list-tools"><span class="count" id="count"></span>${sortControls(type)}</div><div class="grid fade" id="cards"></div>`)}
function paramSummary(x){const names=['HP','MP','ATK','DEF','M.ATK','M.DEF','AGI','LUK'];const p=x.params||[];return names.map((n,i)=>{const v=Number(p[i]||0);if(!v)return '';return `<span class="mini-stat ${v>0?'positive':'negative'}">${n} ${v>0?'+':''}${v}</span>`}).filter(Boolean).join('')||'<span class="mini-stat muted">No stat changes</span>'}
function stateName(id){const s=dataById('states',id);return s?.name?`State: ${s.name}`:`State #${id}`}
function itemEffectSummary(x){const out=[];for(const e of (x.effects||[])){const c=Number(e.code),v2=Number(e.value2||0);if(c===11&&v2)out.push(`Restores ${v2} HP`);else if(c===12&&v2)out.push(`Restores ${v2} MP`);else if(c===13&&v2)out.push(`Restores ${v2}% HP`);else if(c===14&&v2)out.push(`Restores ${v2}% MP`);else if(c===21)out.push(`Adds ${stateName(e.dataId)}`);else if(c===22)out.push(`Removes ${stateName(e.dataId)}`);else if(c===44)out.push('Common Event');}return out.length?out.join(' · '):'No effects'}
function traitSummary(x){const out=[];for(const t of (x.traits||[])){const c=Number(t.code),d=Number(t.dataId),v=Number(t.value||0);if(c===32)out.push(`${['Hit Rate','Evasion','Critical Rate','Critical Evasion','Magic Evasion','Magic Reflection','Counter','HP Regen','MP Regen','TP Regen'][d]||'X-Parameter'} ${v>=0?'+':''}${Math.round(v*100)}%`);else if(c===33)out.push(`${['Target Rate','Guard Effect','Recovery Effect','Pharmacology','MP Cost','TP Charge','Physical Damage','Magical Damage','Floor Damage','Experience'][d]||'S-Parameter'} ${v>=0?'+':''}${Math.round(v*100)}%`);else if(c===22)out.push(`${stateName(d)} rate ${Math.round(v*100)}%`);else if(c===43)out.push(`Adds Skill #${d}`);else if(c===44)out.push('Common Event');}return out.length?out.join(' · '):'No effects'}
function card(type,x){
if(type==='enemies'){const c=enemyCategory(x),p=x.params||[];return `<a class="card card-link ${isSpoiler(x,'enemies')?'spoiler-hidden':''}" data-id="${x.id}" href="#enemies/${encodeURIComponent(x.id)}"><div class="topline">${enemyTag(c)}<span class="zone">${esc(noteTag(x.note,'Tattle Category')||'UNASSIGNED ZONE')}</span></div><div class="enemy-card-copy"><h3>${esc(x.name)}</h3><p>${esc(cleanText(noteTag(x.note,'Info')).slice(0,125)||'Study entry available.')}</p><div class="statline"><span>HP <b>${p[0]??0}</b></span><span>ATK <b>${p[2]??0}</b></span><span>DEF <b>${p[3]??0}</b></span><span class="lv">LV ${levelRange(x)}</span></div></div><img class="enemy-art" src="assets/enemies_src/${encodeURIComponent(x.battlerName||'')}.png" onerror="this.style.display='none'" alt=""></a>`}
if(type==='actors'){return `<a class="card card-link" data-id="${x.id}" href="#actors/${encodeURIComponent(x.id)}"><div class="topline"><span class="tag">Playable Character</span><span class="zone">#${x.id}</span></div><div class="item-title"><img class="actor-art" src="${actorImage(x)}" alt=""><h3>${esc(x.name)}</h3></div><p>${esc(x.name==='Roy'?'Abyss Explorer':x.name==='Dog'?'Doggy':'Willowisp')}</p></a>`}
const r=(type==='weapons'||type==='armors')?parseRarity(x.note):null;const badge=type==='items'?`<span class="tag">${esc(itemCategories[itemCategory(x.id)]?.[0]||'Item')}</span>`:type==='skills'?`<span class="tag">${esc(skillCategory(x.id)==='hero'?'Hero Skill':skillCategory(x.id)==='dog'?'Dog Skill':'Willy Skill')}</span>`:type==='states'?'<span class="tag">Status</span>':'<span class="tag">Database</span>';let art=type==='weapons'?weaponArt(x):'';let preview=(type==='weapons'||type==='armors')?`<div class="mini-stats">${paramSummary(x)}</div><div class="mini-effect">${esc(traitSummary(x))}</div>`:type==='items'?`<div class="mini-effect">${esc(itemEffectSummary(x))}</div>`:`<p>${esc(cleanText(x.description)||'No player-facing description recorded.')}</p>`;return `<a class="card card-link ${isSpoiler(x,type)?'spoiler-hidden':''}" data-id="${x.id}" href="#${type}/${encodeURIComponent(x.id)}"><div class="topline">${type==='weapons'||type==='armors'?rarityTag(r):badge}<span class="zone">#${x.id}</span></div><div class="item-title">${icon(x.iconIndex)}<h3>${esc(x.name)}</h3></div>${art?`<img class="weapon-art" src="${art}" alt="">`:''}${preview}<div class="statline"><span>PRICE <b>${x.price??0}</b></span>${r!=null?`<span style="color:${rarity[r][1]}">T${r}</span>`:''}</div></a>`}

const weaponMap={'Twig':'Stick 1.png','Stick':'Stick 1.png','Old Frying Pan':'Frying Pan.png','Old Wooden Club':'Club.png','Worn-Out Wooden Bat':'Worn-out Bat.png',"Beginner's Bow":'Normal Bow.png','Squeaky Hammer':'Worn out Hammer.png','Magical Cane':'Wand of Energizing Nectar.png','Toy Golf Club':'Golf Club.png','Wooden Bat':'Wooden Bat.png','Short Leaf Sword':'Short Leaf Sword.png','Leafwhipper':'Leafwhipper.png','Wooden Bow':'Normal Bow.png','Worn-Out Hammer':'Worn out Hammer.png','Jello Bello B':'Jello Bello B.png','Wooden Sword':'Wooden Sword.png','Palce Holder (Bow)':'Normal Bow.png','Sharp Dagger':'Dagger.png','Jello Bello R':'Jello Bello R.png','Stony Bow':'Stony Bow.png','The Electronic Hammer':'The Electronic Hammer.png','Wand of Energizing Nectar':'Wand of Energizing Nectar.png','The Hammer of Destruction':'The Hammer of Destruction.png','Sword':'Wooden Sword.png','Axe':'Club.png','Pistol Gun':'Golden Bow.png','Bow':'Normal Bow.png','Worn-Out Dagger':'Dagger.png','Magical Cane TEST':'Wand of Energizing Nectar.png','Sharp Dagger TEST':'Dagger.png','Wand of Energizing Nectar TEST':'Wand of Energizing Nectar.png','Normal Dog Fangs':'Dagger.png',"Willy's Light Fist":'Club.png'};
function weaponArt(x){const f=weaponMap[x.name];return f?`assets/weapons_src/${encodeURIComponent(f)}`:''}
function renderList(type){const q=($('#search')?.value||'').toLowerCase();let arr=type==='enemies'?usedEnemies():type==='actors'?playableActors():type==='weapons'||type==='armors'?equipmentEntries(type):type==='items'?itemEntries():type==='skills'?allPublicSkills():validEntries(type);const active=$('.filter.active')?.dataset.filter;if(type==='enemies'&&active&&active!=='all')arr=arr.filter(e=>enemyCategory(e)===active);if(type==='weapons'||type==='armors'){if(active&&active!=='all')arr=arr.filter(x=>parseRarity(x.note)===Number(active))}if(type==='items'&&active&&active!=='all')arr=arr.filter(x=>itemCategory(x.id)===active);if(type==='skills'&&active&&active!=='all')arr=arr.filter(x=>skillCategory(x.id)===active);arr=arr.filter(x=>`${x.name} ${cleanText(x.description)} ${cleanText(noteTag(x.note,'Info'))}`.toLowerCase().includes(q));const s=$('#sort')?.value||'name-az';arr.sort((a,b)=>sorter(type,s,a,b));$('#count').textContent=`${arr.length} entr${arr.length===1?'y':'ies'}`;$('#cards').innerHTML=arr.map(x=>card(type,x)).join('')||'<div class="empty">No matching entries.</div>';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>location.hash=`#${type}/${c.dataset.id}`)}
function sorter(type,s,a,b){if(s.startsWith('tier'))return ((parseRarity(a.note)??99)-(parseRarity(b.note)??99))*(s==='tier-high'?-1:1);if(s.startsWith('price'))return ((a.price??0)-(b.price??0))*(s==='price-high'?-1:1);if(s==='hp-high')return (b.params?.[0]??0)-(a.params?.[0]??0);if(s==='hp-low')return (a.params?.[0]??0)-(b.params?.[0]??0);if(s==='id-low'||s==='id-high')return (a.id-b.id)*(s==='id-low'?1:-1);return a.name.localeCompare(b.name)*(s==='name-az'?1:-1)}
function enemySkillIds(){const set=new Set();usedEnemies().forEach(e=>(e.actions||[]).forEach(a=>set.add(a.skillId)));return set}
function isSpoiler(x,type){const ids=config.spoilers?.[type];return Array.isArray(ids)&&ids.includes(x.id)||allTags(x.note,'Spoiler').length>0}
function paramRows(x){const names=['HP','MP','ATK','DEF','M.ATK','M.DEF','AGI','LUK'];const p=x.params||[];return `<div class="param-grid">${names.map((n,i)=>`<div class="param-box"><span>${n}</span><strong>${p[i]??0}</strong></div>`).join('')}</div>`}
function enemyElements(e){const rates=(e.traits||[]).filter(t=>t.code===11);const atk=(e.traits||[]).filter(t=>t.code===31);return `<div class="element-box"><div class="element-group"><strong>WEAKNESSES</strong><p>${rates.some(t=>t.value>1)?'Element data present':'N/A'}</p></div><div class="element-group"><strong>RESISTANCES</strong><p>${rates.some(t=>t.value<1)?'Element data present':'N/A'}</p></div><div class="element-group"><strong>ATTACK ELEMENT</strong><p>${atk.length?'Element data present':'N/A'}</p></div><div class="element-group"><strong>TRAITS</strong><p>${(e.traits||[]).length?`${e.traits.length} gameplay traits recorded`:'N/A'}</p></div></div>`}
function statRows(e){const p=e.params||[];const colors=['#e34e78','#b97ae9','#f0c64f','#63b0e9','#bd79ed','#62d58e','#62d58e','#ed4ac7'];const max=Math.max(...p,1);return [['HP',0],['MP',1],['ATK',2],['DEF',3],['M.ATK',4],['M.DEF',5],['AGI',6],['LUK',7]].map(([n,i])=>`<div class="stat-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" data-width="${Math.max(2,Math.round((p[i]||0)/max*100))}%" style="background:${colors[i]}"></div></div><span class="stat-value">${p[i]??0}</span></div>`).join('')}
function enemySkillCards(e){const ids=[...(e.actions||[])].map(a=>a.skillId).filter(Boolean);const unique=[...new Set(ids)];return unique.map(id=>dataById('skills',id)).filter(s=>s&&s.name&&!isHeader(s)).map(s=>`<div class="skill-card"><h4>${esc(s.name)}</h4><p>${esc(cleanText(s.description)||'No player-facing skill description recorded.')}</p></div>`).join('')}
function enemyDetail(e){const info=cleanText(noteTag(e.note,'Info'));const list=usedEnemies();const idx=list.findIndex(x=>x.id===e.id);const prev=list[idx-1],next=list[idx+1];const skills=enemySkillCards(e);return `<div class="detail-page fade"><div class="detail-nav">${prev?`<a href="#enemies/${prev.id}">← <span>Previous</span><span class="nav-name">${esc(prev.name)}</span></a>`:'<span></span>'}${next?`<a href="#enemies/${next.id}"><span class="nav-name">${esc(next.name)}</span><span>Next</span> →</a>`:'<span></span>'}</div><a class="back" href="#enemies">← Back to Enemy Bestiary</a><div class="detail-top"><div class="detail-art"><img src="assets/enemies_src/${encodeURIComponent(e.battlerName||'')}.png" onerror="this.style.display='none'" alt=""></div><div><div>${enemyTag(enemyCategory(e))} <span class="tag">${esc(noteTag(e.note,'Tattle Category')||'Unassigned Zone')}</span></div><h1>${esc(e.name)}</h1><p class="detail-description">Enemy entry from the current development build.</p></div></div><div class="detail-layout"><section class="panel"><div class="panel-title">Base Stats</div>${statRows(e)}<div class="fact-grid"><div class="fact"><strong>${e.exp??0}</strong><small>EXP</small></div><div class="fact"><strong>${e.gold??0}</strong><small>GOLD</small></div><div class="fact"><strong>${levelRange(e)}</strong><small>LEVEL</small></div></div></section><section class="panel"><div class="panel-title">Study</div><div class="study-box"><p>${esc(info||'No Study entry recorded yet.')}</p></div></section><section class="panel"><div class="panel-title">Weaknesses & Traits</div>${enemyElements(e)}<div class="notice">Element names remain N/A until the game's element-name source is included. Internal RPG Maker notetags are not displayed here.</div></section><section class="panel"><div class="panel-title">Enemy Skills</div>${skills?`<div class="skill-list">${skills}</div>`:'<p class="detail-description">No named enemy skills are currently recorded for this enemy.</p>'}</section></div></div>`}
function equipmentEffects(x){return `<section class="panel"><div class="panel-title">Effects</div><p class="detail-description">${esc(traitSummary(x))}</p></section>`}
function genericDetail(type,x){if(type==='actors')return actorDetail(x);const r=(type==='weapons'||type==='armors')?parseRarity(x.note):null;let body='';if(type==='weapons'||type==='armors'){body=`<section class="panel"><div class="panel-title">Parameters</div>${paramRows(x)}</section><section class="panel"><div class="panel-title">Equipment Details</div><div class="data-list"><div class="data-row"><span class="data-label">Database ID</span><span class="data-value">#${x.id}</span></div><div class="data-row"><span class="data-label">Price</span><span class="data-value">${x.price??0}</span></div><div class="data-row"><span class="data-label">Tier</span><span class="data-value">${r!=null?`${rarity[r][0]} · Tier ${r}`:'Unassigned'}</span></div></div></section>${equipmentEffects(x)}`}else if(type==='items'){body=`<section class="panel"><div class="panel-title">Item Details</div><div class="data-list"><div class="data-row"><span class="data-label">Category</span><span class="data-value">${esc(itemCategories[itemCategory(x.id)]?.[0]||'Item')}</span></div><div class="data-row"><span class="data-label">Database ID</span><span class="data-value">#${x.id}</span></div></div></section><section class="panel"><div class="panel-title">Effects</div><p class="detail-description">${esc(itemEffectSummary(x))}</p></section>`}else if(type==='skills'){body=`<section class="panel"><div class="panel-title">Skill Details</div><div class="data-list"><div class="data-row"><span class="data-label">Category</span><span class="data-value">${skillCategory(x.id)==='hero'?'Hero Skills':skillCategory(x.id)==='dog'?'Dog Skills':'Willy Skills'}</span></div></div></section>`}else{body=`<section class="panel"><div class="panel-title">Entry Details</div><div class="data-list"><div class="data-row"><span class="data-label">Database ID</span><span class="data-value">#${x.id}</span></div></div></section>`}return `<div class="detail-page fade"><a class="back" href="#${type}">← Back to ${typeTitle(type)}</a><div class="detail-top"><div class="detail-art">${detailArt(type,x)}</div><div><div>${(type==='weapons'||type==='armors')?rarityTag(r):`<span class="tag">${type==='items'?itemCategories[itemCategory(x.id)]?.[0]||'Item':type==='skills'?'Player Skill':typeTitle(type)}</span>`}</div><h1>${esc(x.name)}</h1><p class="detail-description item-detail-description">${esc(cleanText(x.description)||'No player-facing description recorded.')}</p></div></div><div class="detail-layout">${body}</div></div>`}
function actorDetail(a){const c=dataById('classes',a.classId);const skills=playableSkills(a.name==='Roy'?'hero':a.name==='Dog'?'dog':'willy');return `<div class="detail-page fade"><a class="back" href="#actors">← Back to Characters</a><div class="detail-top"><div class="detail-art"><img class="actor-art" src="${actorImage(a)}" alt="${esc(a.name)}"></div><div><span class="tag">${a.name==='Roy'?'Protagonist':'Partner'}</span><h1>${esc(a.name)}</h1><p class="detail-description">${esc(c?.name||'Current playable party member.')}</p></div></div><div class="detail-layout"><section class="panel"><div class="panel-title">Class</div><div class="data-list"><div class="data-row"><span class="data-label">Class</span><span class="data-value">${esc(c?.name||'—')}</span></div><div class="data-row"><span class="data-label">Actor ID</span><span class="data-value">#${a.id}</span></div></div></section><section class="panel"><div class="panel-title">Skills</div><div class="skill-list">${skills.map(s=>`<div class="skill-card"><h4>${esc(s.name)}</h4><p>${esc(cleanText(s.description)||'No player-facing description recorded.')}</p></div>`).join('')||'<p class="detail-description">No player-facing skills recorded.</p>'}</div></section></div></div>`}
function detailArt(type,x){if(type==='weapons'){const f=weaponArt(x);return f?`<img src="${f}" alt="">`:icon(x.iconIndex)}if(type==='actors')return `<img class="actor-art" src="${actorImage(x)}" alt="">`;return icon(x.iconIndex)}
function typeTitle(t){return ({weapons:'Weapons',armors:'Armor & Accessories',items:'Items',skills:'Skills',states:'Status Effects',actors:'Characters',enemies:'Enemy Bestiary'})[t]||t}
function itemFilters(){return [['all','All'],...Object.entries(itemCategories).map(([k,v])=>[k,v[0]])]}
function skillFilters(){return [['all','All'],['hero','Hero Skills'],['dog','Dog Skills'],['willy','Willy Skills']]}
function page(type){if(type==='home')return home();if(type.startsWith('search/'))return searchPage(decodeURIComponent(type.slice(7)));if(type.includes('/')){const [t,id]=type.split('/');const x=dataById(t,id);if(!x||!x.name)return shell(t,'<div class="empty">Entry not found.</div>');if(t==='enemies')return shell(t,enemyDetail(x));return shell(t,genericDetail(t,x))}const meta={enemies:['Enemy Bestiary',`${usedEnemies().length} named enemies currently referenced by Troops.json. Study information is separated from the page header.`],weapons:['Weapons',`${equipmentEntries('weapons').length} weapons with assigned game tiers. Plugin rarity 1–7 is displayed as game Tier 0–6.`],armors:['Armor & Accessories',`${equipmentEntries('armors').length} armor/accessory entries with assigned game tiers.`],items:['Items',`${itemEntries().length} items organized into the RPG Maker sections used by the current database.`],skills:['Skills',`${allPublicSkills().length} player-facing skills organized into Hero, Dog, and Willy sections.`],states:['Status Effects','Status effects from the current database. Used-state selection can be refined later.'],actors:['Characters','The playable party members in the current actor setup.']};const m=meta[type];if(!m)return home();let filters=null;if(type==='enemies')filters=[['all','All'],['normal','Normal'],['champion','Champion'],['elite','Elite'],['elite champion','Elite Champion'],['mini boss','Mini Boss'],['boss','Boss'],['abyss normal','Abyss · Normal'],['abyss champion','Abyss · Champion'],['abyss elite','Abyss · Elite'],['abyss elite champion','Abyss · Elite Champion'],['abyss mini boss','Abyss · Mini Boss'],['abyss boss','Abyss · Boss'],['uncategorized','Uncategorized']];if(type==='weapons'||type==='armors')filters=[['all','All'],...rarityOrder.map(r=>[String(r),`T${r} · ${rarity[r][0]}`])];if(type==='items')filters=itemFilters();if(type==='skills')filters=skillFilters();return listPage(type,m[0],m[1],filters)}
function searchPage(q){const groups=[['Enemies','enemies',usedEnemies()],['Weapons','weapons',equipmentEntries('weapons')],['Armor','armors',equipmentEntries('armors')],['Items','items',itemEntries()],['Skills','skills',allPublicSkills()],['Status Effects','states',validEntries('states')],['Characters','actors',playableActors()]];const needle=q.trim().toLowerCase();let html='';for(const [title,type,arr] of groups){const hits=arr.filter(x=>`${x.name} ${cleanText(x.description)} ${cleanText(noteTag(x.note,'Info'))}`.toLowerCase().includes(needle));if(hits.length)html+=`<section class="recent"><div class="section-title">${title}</div><div class="grid">${hits.slice(0,9).map(x=>card(type,x)).join('')}</div></section>`}return shell('',`<div class="page-head fade"><div><div class="page-kicker">Global Search</div><h1 class="page-title">Search Results</h1><p class="page-desc">Results for “${esc(q)}” across the public encyclopedia catalog.</p></div></div>${html||'<div class="empty">No matching entries.</div>'}`)}
async function load(){for(const f of DB)db[f]=await fetch(`data/${f}.json`).then(r=>r.json());config=await fetch('data/site-config.json').then(r=>r.json());usedIds=(await fetch('data/enemy-used-ids.json').then(r=>r.json())).usedEnemyIds||[];applyPrefs();route()}
function bindGlobal(){const form=$('#globalSearch');if(form)form.onsubmit=e=>{e.preventDefault();const q=$('#globalSearchInput').value.trim();if(q)location.hash='#search/'+encodeURIComponent(q)}}
function bindAccess(){const s=$('#spoilerToggle');if(s)s.onclick=()=>{localStorage.setItem('ie-spoilers',spoilerEnabled()?'off':'on');route()};document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{localStorage.setItem('ie-text-zoom',b.dataset.zoom);route()});}
function route(){const raw=(location.hash||'#home').slice(1)||'home';document.body.innerHTML=page(raw);applyPrefs();window.scrollTo({top:0,left:0,behavior:'auto'});nav(raw.split('/')[0]);bindGlobal();bindAccess();if(!raw.includes('/')&&raw!=='home'){const base=raw;renderList(base);$('#search')?.addEventListener('input',()=>renderList(base));$('#sort')?.addEventListener('change',()=>renderList(base));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderList(base)})}if(raw.includes('/')&&raw.split('/')[0]==='enemies')setTimeout(animateBars,70)}
function animateBars(){document.querySelectorAll('.bar-fill').forEach((b,i)=>requestAnimationFrame(()=>setTimeout(()=>b.style.width=b.dataset.width,i*45)))}
window.addEventListener('hashchange',route);load();
